import { env } from 'cloudflare:workers';
import { eq, sql } from 'drizzle-orm';
import { syncState, tasks, weeklyActivities } from '@/db/schema';
import { database, ensureDatabase } from '@/lib/db';

type Photo = { file_id: string; width: number; height: number };
type Message = { text?: string; caption?: string; photo?: Photo[]; chat: { id: number } };
type Update = { update_id: number; message?: Message };
type AiActivity = { day: string; title: string; start: string; end: string };
type Pending = { title: string; startAt: string; endAt: string };
class PhotoReadError extends Error { constructor(public kind: 'telegram'|'key'|'quota'|'gemini'|'format') { super(kind); } }
const weekdays: Record<string, number> = { sunday:0,sun:0,monday:1,mon:1,tuesday:2,tue:2,tues:2,wednesday:3,wed:3,thursday:4,thu:4,thurs:4,friday:5,fri:5,saturday:6,sat:6 };

function parseTime(value:string) { const match=value.trim().match(/^(\d{1,2})(?::(\d{2}))?\s*(am|pm)?$/i); if(!match)return null; let hour=Number(match[1]); const minute=Number(match[2]||0); const meridiem=match[3]?.toLowerCase(); if(minute>59||hour>(meridiem?12:23))return null; if(meridiem==='pm'&&hour!==12)hour+=12; if(meridiem==='am'&&hour===12)hour=0; return hour*60+minute; }
function nextDateFor(day:number, minute:number) { const now=new Date(); const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Detroit',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'}).formatToParts(now); const part=(type:Intl.DateTimeFormatPartTypes)=>parts.find(item=>item.type===type)?.value||''; const delta=(day-weekdays[part('weekday').toLowerCase()]+7)%7; const base=new Date(`${part('year')}-${part('month')}-${part('day')}T12:00:00-04:00`); base.setDate(base.getDate()+delta); const date=`${base.getFullYear()}-${String(base.getMonth()+1).padStart(2,'0')}-${String(base.getDate()).padStart(2,'0')}`; const noon=new Date(`${date}T12:00:00-04:00`); const offset=new Intl.DateTimeFormat('en-US',{timeZone:'America/Detroit',timeZoneName:'longOffset'}).formatToParts(noon).find(item=>item.type==='timeZoneName')?.value.replace('GMT','')||'-04:00'; return new Date(`${date}T${String(Math.floor(minute/60)).padStart(2,'0')}:${String(minute%60).padStart(2,'0')}:00${offset}`); }
function normalize(item:AiActivity):Pending|null { const day=weekdays[item.day?.trim().toLowerCase()]; const start=parseTime(item.start||''); const end=parseTime(item.end||''); if(day===undefined||start===null||end===null||end<=start||!item.title?.trim())return null; return {title:item.title.trim().slice(0,200),startAt:nextDateFor(day,start).toISOString(),endAt:nextDateFor(day,end).toISOString()}; }
function parseLine(line:string) { const parts=line.split('|').map(part=>part.trim()).filter(Boolean); if(parts.length!==3)return null; const range=parts[2].split(/\s*(?:-|–|to)\s*/i); return normalize({day:parts[0],title:parts[1],start:range[0]||'',end:range[1]||''}); }
async function telegram(token:string,method:string,body:Record<string,unknown>) { return fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); }
async function reply(token:string,chatId:string,text:string) { await telegram(token,'sendMessage',{chat_id:chatId,text}); }
async function getPhoto(token:string,photo:Photo) { const response=await telegram(token,'getFile',{file_id:photo.file_id}); const payload=await response.json() as {ok:boolean;result?:{file_path?:string}}; if(!payload.ok||!payload.result?.file_path)throw new PhotoReadError('telegram'); const image=await fetch(`https://api.telegram.org/file/bot${token}/${payload.result.file_path}`); if(!image.ok)throw new PhotoReadError('telegram'); const bytes=new Uint8Array(await image.arrayBuffer()); let binary=''; for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000)); return {data:btoa(binary),mimeType:image.headers.get('content-type')||'image/jpeg'}; }
async function readImage(apiKey:string,image:{data:string;mimeType:string},caption='') { const today=new Intl.DateTimeFormat('en-US',{timeZone:'America/Detroit',dateStyle:'full'}).format(new Date()); const prompt=`Read this schedule image for Tarik. Today is ${today}. Extract only upcoming after-school or personal activities with a clear weekday, name, start time, and end time. Do not include school bell periods. ${caption?`Context: ${caption}`:''} Return JSON only: {"activities":[{"day":"Monday","title":"Football practice","start":"3:30 PM","end":"5:30 PM"}],"note":"short explanation if unclear"}. If nothing is reliable, return an empty activities array.`; let response:Response|null=null; for(let attempt=0;attempt<3;attempt++){response=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent',{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({contents:[{parts:[{text:prompt},{inline_data:{mime_type:image.mimeType,data:image.data}}]}],generationConfig:{responseMimeType:'application/json',temperature:.1}})}); if(response.ok)break; if(response.status!==429&&response.status<500)break; await new Promise(resolve=>setTimeout(resolve,500*(attempt+1)));} if(!response?.ok){if(response?.status===401||response?.status===403)throw new PhotoReadError('key');if(response?.status===429)throw new PhotoReadError('quota');throw new PhotoReadError('gemini');} const payload=await response.json() as {candidates?:Array<{content?:{parts?:Array<{text?:string}>}}>} ; try{return JSON.parse(payload.candidates?.[0]?.content?.parts?.map(part=>part.text||'').join('')||'{}') as {activities?:AiActivity[];note?:string};}catch{throw new PhotoReadError('format');} }
function confirmation(items:Pending[],note?:string) { const date=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'short',day:'numeric',timeZone:'America/Detroit'}); const time=new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit',timeZone:'America/Detroit'}); return `I found:\n${items.map(item=>`• ${item.title} — ${date.format(new Date(item.startAt))}, ${time.format(new Date(item.startAt))}–${time.format(new Date(item.endAt))}`).join('\n')}${note?`\n\nNote: ${note}`:''}\n\nReply YES to add these to your dashboard, or NO to cancel.`; }

export async function POST() {
  const token=String(env.TELEGRAM_BOT_TOKEN||''); const chat=String(env.TELEGRAM_CHAT_ID||''); const key=String(env.GEMINI_API_KEY||'');
  if(!token||!chat)return Response.json({configured:false,aiConfigured:Boolean(key),imported:0,activitiesImported:0});
  await ensureDatabase(); const db=database(); const [offsetRows,pendingRows]=await Promise.all([db.select().from(syncState).where(eq(syncState.key,'telegram_offset')),db.select().from(syncState).where(eq(syncState.key,'telegram_pending_activities'))]); const offset=Number(offsetRows[0]?.value||0); let pending:Pending[]=[]; try{pending=JSON.parse(pendingRows[0]?.value||'[]');}catch{pending=[];}
  const url=new URL(`https://api.telegram.org/bot${token}/getUpdates`); url.searchParams.set('offset',String(offset)); url.searchParams.set('limit','100'); url.searchParams.set('timeout','0'); url.searchParams.set('allowed_updates',JSON.stringify(['message'])); const response=await fetch(url); if(!response.ok)return Response.json({configured:true,error:'Telegram could not be reached.'},{status:502}); const payload=await response.json() as {ok:boolean;result:Update[]}; if(!payload.ok)return Response.json({configured:true,error:'Telegram rejected the sync.'},{status:502});
  const updates=payload.result.filter(update=>String(update.message?.chat.id||'')===chat); const taskValues:Array<{title:string;source:string;externalId:string}>=[]; const activityValues:Array<{title:string;startAt:Date;endAt:Date;source:string;externalId:string}>=[];
  for(const update of updates){const message=update.message!;const text=message.text?.trim()||'';if(pending.length&&/^(yes|y|add them|confirm)$/i.test(text)){pending.forEach((item,index)=>activityValues.push({title:item.title,startAt:new Date(item.startAt),endAt:new Date(item.endAt),source:'telegram-ai',externalId:`telegram-ai:${update.update_id}:${index}`}));pending=[];await reply(token,chat,'Added to your weekly dashboard ✅');continue;}if(pending.length&&/^(no|n|cancel)$/i.test(text)){pending=[];await reply(token,chat,'Canceled — nothing was added.');continue;}if(message.photo?.length){if(!key){await reply(token,chat,'Photo reading is not configured yet. Add the Gemini API key first.');continue;}try{const result=await readImage(key,await getPhoto(token,message.photo[message.photo.length-1]),message.caption||'');pending=(result.activities||[]).map(normalize).filter((item):item is Pending=>Boolean(item));await reply(token,chat,pending.length?confirmation(pending,result.note):`I could read the picture, but I couldn't find activities with both a start and end time.${result.note?` ${result.note}`:''}`);}catch(error){const kind=error instanceof PhotoReadError?error.kind:'gemini';const messages={telegram:'Telegram could not download that photo. Please send it again as a photo.',key:'The Gemini key was rejected. Check the key in Cloudflare or create a new restricted Gemini key.',quota:'Gemini’s free limit is busy or exhausted. Please try again in a minute.',gemini:'Gemini is temporarily unavailable. Please try the same picture again shortly.',format:'Gemini read the picture but returned an unexpected format. Please resend it once.'};await reply(token,chat,messages[kind]);}continue;}if(/^schedule\s*:/i.test(text)){text.replace(/^schedule\s*:/i,'').split(/\n+/).map(line=>line.trim()).filter(Boolean).forEach((line,index)=>{const item=parseLine(line);if(item)activityValues.push({title:item.title,startAt:new Date(item.startAt),endAt:new Date(item.endAt),source:'telegram',externalId:`telegram:${update.update_id}:${index}`});});continue;}if(text&&!text.startsWith('/'))taskValues.push({title:text.slice(0,500),source:'telegram',externalId:`telegram:${update.update_id}`});}
  if(taskValues.length)await db.insert(tasks).values(taskValues).onConflictDoNothing(); if(activityValues.length)await db.insert(weeklyActivities).values(activityValues).onConflictDoNothing(); const nextOffset=payload.result.length?Math.max(...payload.result.map(update=>update.update_id))+1:offset; await db.batch([db.insert(syncState).values({key:'telegram_offset',value:String(nextOffset)}).onConflictDoUpdate({target:syncState.key,set:{value:sql`excluded.value`}}),db.insert(syncState).values({key:'telegram_pending_activities',value:JSON.stringify(pending)}).onConflictDoUpdate({target:syncState.key,set:{value:sql`excluded.value`}})]);
  return Response.json({configured:true,aiConfigured:Boolean(key),imported:taskValues.length,activitiesImported:activityValues.length,awaitingConfirmation:pending.length>0});
}
