'use client';

import { CalendarClock, Check, Loader2, MessageCircle, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { fireConfetti } from '@/lib/confetti';

type Activity = { id: number; title: string; startAt: string; endAt: string; completed: boolean };
const dayFormat = new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'short', day: 'numeric', timeZone: 'America/Detroit' });
const timeFormat = new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit', timeZone: 'America/Detroit' });

export function WeeklyActivities() {
  const [activities, setActivities] = useState<Activity[]>([]);
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { const from = new Date(); from.setHours(0, 0, 0, 0); const to = new Date(from); to.setDate(to.getDate() + 8); const response = await fetch(`/api/activities?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`); if (response.ok) setActivities((await response.json()).activities); setLoading(false); }, []);
  useEffect(() => { void load(); const timer = window.setInterval(load, 8_000); window.addEventListener('focus', load); return () => { window.clearInterval(timer); window.removeEventListener('focus', load); }; }, [load]);
  const groups = useMemo(() => Object.entries(activities.reduce<Record<string, Activity[]>>((result, activity) => { const key = dayFormat.format(new Date(activity.startAt)); (result[key] ||= []).push(activity); return result; }, {})), [activities]);
  async function toggle(activity: Activity, source: HTMLElement) { const completed = !activity.completed; if (completed) { const box = source.getBoundingClientRect(); fireConfetti({ x: box.left + box.width / 2, y: box.top + box.height / 2 }); } setActivities((items) => items.map((item) => item.id === activity.id ? { ...item, completed } : item)); const response = await fetch('/api/activities', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: activity.id, completed }) }); if (!response.ok) void load(); }
  async function remove(id: number) { setActivities((items) => items.filter((item) => item.id !== id)); const response = await fetch(`/api/activities?id=${id}`, { method: 'DELETE' }); if (!response.ok) void load(); }
  return <section data-dashboard-section="activities" className="dashboard-card overflow-hidden"><div className="flex items-center justify-between border-b border-border/70 px-5 py-4 sm:px-6"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><CalendarClock className="size-4" /></div><div><p className="eyebrow">After school & more</p><h2 className="mt-0.5 font-semibold tracking-tight">This week</h2></div></div><span className="flex items-center gap-1.5 text-[10px] text-muted-foreground"><MessageCircle className="size-3" /> Telegram</span></div>{loading ? <div className="flex items-center justify-center gap-2 px-5 py-10 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin" /> Loading your week</div> : groups.length === 0 ? <div className="px-5 py-9 text-center"><p className="font-medium">Your week is clear.</p><p className="mt-1 text-xs text-muted-foreground">Send <strong>schedule:</strong> followed by your plans to the Telegram bot.</p></div> : <div className="divide-y divide-border/70">{groups.map(([day, items]) => <div key={day} className="px-5 py-4 sm:px-6"><p className="mb-2 text-[10px] font-bold uppercase tracking-[.14em] text-cyan-300">{day}</p>{items.map((activity) => <div key={activity.id} className="group flex items-center gap-3 py-2"><button onClick={(event) => toggle(activity, event.currentTarget)} className={`check-circle ${activity.completed ? 'check-circle-done' : ''}`} aria-label={activity.completed ? `Mark ${activity.title} incomplete` : `Complete ${activity.title}`}>{activity.completed && <Check />}</button><button onClick={(event) => toggle(activity, event.currentTarget)} className="min-w-0 flex-1 text-left"><span className={`block text-sm font-medium ${activity.completed ? 'text-muted-foreground line-through' : ''}`}>{activity.title}</span><span className="mt-0.5 block text-xs text-muted-foreground">{timeFormat.format(new Date(activity.startAt))}–{timeFormat.format(new Date(activity.endAt))}</span></button><button onClick={() => remove(activity.id)} className="rounded-lg p-2 text-muted-foreground opacity-60 transition hover:bg-secondary hover:text-foreground sm:opacity-0 sm:group-hover:opacity-100" aria-label={`Delete ${activity.title}`}><Trash2 className="size-4" /></button></div>)}</div>)}</div>}</section>;
}
